import React, { useEffect, useRef, useState } from 'react'
import api from '../api'
import { useParams, useNavigate } from 'react-router-dom'
import { MEMORY_WORDS } from '../utils/constants'

type Stage = 'memory-display' | 'memory-test' | 'pairs' | 'numbers' | 'camera' | 'complete'
type Card = { id: number; color: string; open: boolean; matched: boolean }
const COLORS = ['#e16f4d', '#147d7e', '#f1bd48', '#6d5aa8', '#2c8c5a', '#d94f70', '#4776b5', '#9c6b30']
const shuffle = <T,>(items: T[]) => [...items].sort(() => Math.random() - 0.5)

export default function Cognitive() {
  const { id } = useParams<{ id: string }>(); const navigate = useNavigate()
  const [words, setWords] = useState<string[]>(MEMORY_WORDS); const [stage, setStage] = useState<Stage>('memory-display')
  const [time, setTime] = useState(15); const [recalled, setRecalled] = useState<string[]>([]); const [entry, setEntry] = useState('')
  const [cards, setCards] = useState<Card[]>(() => shuffle(COLORS.flatMap((color, pair) => [{ id: pair * 2, color, open: false, matched: false }, { id: pair * 2 + 1, color, open: false, matched: false }])))
  const [first, setFirst] = useState<number | null>(null); const [moves, setMoves] = useState(0)
  const [grid] = useState(() => shuffle(Array.from({ length: 25 }, (_, n) => n + 1))); const [next, setNext] = useState(1)
  const [started, setStarted] = useState<number | null>(null); const [stopped, setStopped] = useState<number | null>(null)
  const [cameraPhase, setCameraPhase] = useState<'memory' | 'colors' | 'record' | 'done'>('memory'); const [cameraTime, setCameraTime] = useState(10)
  const [cameraWords] = useState(() => shuffle(['lantern', 'garden', 'silver'])); const [cameraNumber] = useState(() => Math.floor(Math.random() * 5) + 3)
  const [actionStarted, setActionStarted] = useState<number | null>(null); const [actionEnded, setActionEnded] = useState<number | null>(null); const [capturedWords, setCapturedWords] = useState<string[]>([]); const [cameraError, setCameraError] = useState('')
  const video = useRef<HTMLVideoElement | null>(null); const stream = useRef<MediaStream | null>(null); const recorder = useRef<MediaRecorder | null>(null); const speechRecognition = useRef<any>(null); const chunks = useRef<Blob[]>([])

  useEffect(() => { if (id) api.get(`/cognitive/session/${id}`).then(({ data }) => { if (data.memory?.words?.length) setWords(data.memory.words) }).catch(() => {}) }, [id])
  useEffect(() => { if (stage !== 'memory-display' || time <= 0) return; const timer = window.setTimeout(() => setTime(value => value - 1), 1000); return () => window.clearTimeout(timer) }, [stage, time])
  useEffect(() => { if (stage === 'memory-display' && time === 0) setStage('memory-test') }, [stage, time])
  useEffect(() => { if (stage === 'pairs' && cards.every(card => card.matched)) setStage('numbers') }, [cards, stage])
  useEffect(() => { if (stage === 'camera' && video.current && stream.current) video.current.srcObject = stream.current }, [stage])
  useEffect(() => { if (stage !== 'camera') return; if (cameraTime === 0) { if (cameraPhase === 'memory') { setCameraPhase('colors'); setCameraTime(5) } else if (cameraPhase === 'colors') { startRecording(); setActionStarted(Date.now()); setCameraPhase('record'); setCameraTime(8) } else if (cameraPhase === 'record') { setActionEnded(Date.now()); stopRecording(); setCameraPhase('done') }; return }; const timer = window.setTimeout(() => setCameraTime(value => value - 1), 1000); return () => window.clearTimeout(timer) }, [stage, cameraPhase, cameraTime])
  useEffect(() => () => stream.current?.getTracks().forEach(track => track.stop()), [])

  const addWord = () => { if (entry.trim()) { setRecalled(current => [...current, entry.trim()]); setEntry('') } }
  const flip = (index: number) => { if (cards[index].open || cards[index].matched) return; setCards(current => current.map((card, i) => i === index ? { ...card, open: true } : card)); if (first === null) { setFirst(index); return }; setMoves(value => value + 1); const match = cards[first].color === cards[index].color; if (match) setCards(current => current.map((card, i) => i === first || i === index ? { ...card, matched: true } : card)); else window.setTimeout(() => setCards(current => current.map((card, i) => i === first || i === index ? { ...card, open: false } : card)), 600); setFirst(null) }
  const clickNumber = (value: number) => { if (started === null || stopped !== null || value !== next) return; if (value === 25) setStopped(Date.now()); setNext(number => number + 1) }
  const startNumbers = () => { setStarted(Date.now()); setStopped(null); setNext(1) }
  const startCamera = async () => { try { const current = await navigator.mediaDevices.getUserMedia({ video: true, audio: true }); stream.current = current; if (video.current) video.current.srcObject = current; setCameraError(''); setCameraTime(10); setCameraPhase('memory'); setStage('camera') } catch { setCameraError('Camera and microphone access is required for this session.') } }
  const startRecording = () => { if (!stream.current || typeof MediaRecorder === 'undefined') return; chunks.current = []; const current = new MediaRecorder(stream.current); current.ondataavailable = event => { if (event.data.size) chunks.current.push(event.data) }; current.start(); recorder.current = current; const Recognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition; if (Recognition) { const recognition = new Recognition(); recognition.continuous = true; recognition.interimResults = false; recognition.onresult = (event: any) => { const transcript = Array.from({ length: event.results.length }, (_, index) => event.results[index][0].transcript).join(' '); setCapturedWords(transcript.toLowerCase().split(/[,\s]+/).filter(Boolean)) }; recognition.start(); speechRecognition.current = recognition } }
  const stopRecording = () => { if (recorder.current?.state === 'recording') recorder.current.stop(); speechRecognition.current?.stop(); speechRecognition.current = null }
  const submit = async () => { const payload = { recalled_words: recalled, attention_answer: '', visual_memory: {}, pattern_recognition: [], orientation: {}, story_answers: [], game_results: { pair_game: { matched_pairs: 8, moves }, number_game: { completed: next > 25, elapsed_ms: started && stopped ? stopped - started : null }, camera_session: { expected_words: cameraWords, recalled_words: capturedWords, expected_number: cameraNumber, action_duration_ms: actionStarted && actionEnded ? actionEnded - actionStarted : null, recording_captured: chunks.current.length > 0, capture_verified: chunks.current.length > 0 && !!actionStarted && !!actionEnded } } }; try { await api.post(`/cognitive/submit/${id}`, payload); navigate(`/assessment/speech/${id}`) } catch (error: any) { alert(error?.response?.data?.error || 'Failed to submit cognitive tests') } }

  return <div className="cognitive-page"><header className="page-intro"><div className="eyebrow">COGNITIVE ASSESSMENT / STEP 03</div><h1>Memory in motion</h1><p>Complete each short challenge. Your responses are recorded as one assessment session.</p></header>
    {stage === 'memory-display' && <section className="game-panel memory-panel"><h2>Remember these words</h2><p>You have {time} seconds.</p><div className="memory-word-grid">{words.map(word => <strong key={word}>{word}</strong>)}</div><div className="game-countdown">{time}s</div></section>}
    {stage === 'memory-test' && <section className="game-panel"><h2>Recall the words</h2><p>Add each word you remember.</p><div className="recall-entry"><input value={entry} onChange={event => setEntry(event.target.value)} onKeyDown={event => event.key === 'Enter' && addWord()} placeholder="Type a word" /><button onClick={addWord}>Add word</button></div><div className="recall-list">{recalled.map((word, index) => <button key={`${word}-${index}`} onClick={() => setRecalled(current => current.filter((_, i) => i !== index))}>{word} x</button>)}</div><button className="primary-action" onClick={() => setStage('pairs')}>Continue to pair game <span>-&gt;</span></button></section>}
    {stage === 'pairs' && <section className="game-panel"><h2>Pair up the color cards</h2><p>Flip one card at a time and find all eight pairs.</p><div className="pair-grid">{cards.map((card, index) => <button className={`pair-card ${card.open || card.matched ? 'revealed' : ''}`} key={card.id} onClick={() => flip(index)} style={card.open || card.matched ? { backgroundColor: card.color } : undefined}>{card.open || card.matched ? '' : '?'}</button>)}</div><p className="game-status">Pairs found: {cards.filter(card => card.matched).length / 2} / 8 · Moves: {moves}</p></section>}
    {stage === 'numbers' && <section className="game-panel"><h2>Count from 1 to 25</h2><p>Press Start, then select the numbers in order. Stop ends the timer.</p><div className="number-actions"><button className="primary-action" onClick={startNumbers}>Start</button><button className="secondary-action" onClick={() => started && setStopped(Date.now())}>Stop</button></div><div className="number-grid">{grid.map(number => <button className={number < next ? 'number-done' : ''} key={number} onClick={() => clickNumber(number)}>{number}</button>)}</div><p className="game-status">Next: {next > 25 ? 'Complete' : next}</p>{stopped && <button className="primary-action" onClick={startCamera}>Continue to camera session <span>-&gt;</span></button>}</section>}
    {stage === 'camera' && <section className="game-panel camera-panel"><h2>Camera memory session</h2><video ref={video} autoPlay muted playsInline />{cameraPhase === 'memory' && <div className="camera-prompt"><p>Remember these words and show this number with your fingers.</p><strong>{cameraWords.join(' · ')}</strong><b>{cameraNumber}</b></div>}{cameraPhase === 'colors' && <div className="camera-prompt"><p>Watch the colors carefully.</p><div className="color-flash"><i /><i /><i /></div></div>}{cameraPhase === 'record' && <div className="camera-prompt"><p>Recording now. Say the three words and show {cameraNumber} with your fingers.</p><strong>Capture time remaining: {cameraTime}s</strong><span>Keep your face and hands visible in the camera frame.</span></div>}{cameraPhase === 'done' && <div className="camera-prompt"><p>Camera and microphone capture complete.</p><strong>Captured for verification</strong><p>Recorded action duration: {actionStarted && actionEnded ? `${((actionEnded - actionStarted) / 1000).toFixed(1)} seconds` : 'Unavailable'}</p><p>The recording will be analyzed against the displayed words and finger-number instruction.</p><button className="primary-action" onClick={() => setStage('complete')}>Use captured session <span>-&gt;</span></button></div>}<div className="game-countdown">{cameraPhase === 'done' ? 'Captured' : `${cameraTime}s`}</div>{cameraError && <p className="form-error">{cameraError}</p>}</section>}
    {stage === 'complete' && <section className="game-panel"><h2>Cognitive games complete</h2><p>Your game results and camera response are ready to submit.</p><button className="primary-action" onClick={submit}>Submit cognitive tests <span>-&gt;</span></button></section>}
  </div>
}
